### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Vponed** [nadermx/backgroundremover#161]
backgroundremover -i "/home/Видео/Captures/VID_20241126_055501.mp4" -wn 8 -tv -o '/home/Видео/Captures/output1.mov'
FRAME RATE DETECTED: 149/6 (if this looks wrong, override the frame rate)
FRAME RATE: 25 TOTAL FRAMES: 4151
WORKER 5 ONLINE
WORKER 1 ONLINE
WORKER 6 ONLINE
WORKER 2 ONLINE
WORKER 4 ONLINE
WORKER FRAMERIPPER ONLINE
WORKER 7 ONLINE
WORKER 3 ONLINE
WORKER 0 ONLINE
ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 36352 kb/s
  Stream #0:0: Video: rawvideo (Y800 / 0x30303859), gray, 568x320, 36352 kb/s, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> mpeg4 (native))
Output #0, mp4, to '/tmp/tmpuvli8d72/matte.mp4':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: mpeg4 (mp4v / 0x7634706D), yuv420p(tv, progressive), 568x320, q=2-31, 2000 kb/s, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc59.37.100 mpeg4
    Side data:
      cpb: bitrate max/min/avg: 0/0/2000000 buffer size: 0 vbv_delay: N/A
Traceback (most recent call last): 5888kB time=00:02:18.20 bitrate= 349.0kbits/s speed=0.0714x    
  File "/home/Program/backgroundremover/.venv/bin/backgroundremover", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/Program/backgroundremover/.venv/lib/python3.11/site-packages/backgroundremover/cmd/cli.py", line 196, in main
    utilities.transparentvideo(os.path.abspath(args.output.name), os.path.abspath(args.input.name),
  File "/home/Program/backgroundremover/.venv/lib/python3.11/site-packages/backgroundremover/utilities.py", line 251, in transparentvideo
    matte_key(temp_file, file_path,
  File "/home/Program/backgroundremover/.venv/lib/python3.11/site-packages/backgroundremover/utilities.py", line 135, in matte_key
    while hash_index not in results_dict:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in __contains__
  File "/usr/lib/python3.11/multiprocessing/managers.py", line 822, in _callmethod
    kind, result = conn.recv()
                   ^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 249, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 378, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
frame= 3460 fps=1.8 q=2.0 Lsize=    6165kB time=00:02:18.36 bitrate= 365.0kbits/s speed=0.0715x    
video:6150kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.253577%

**Comment by nadermx** [comment]
can you try changing the file name, to see if that fixes it? What version of ffmpeg are you using as well?

**Comment by nadermx** [comment]
pip install --upgrade backgroundremover
