### ISSUE TITLE
Mac/M1 build using conda throws runtime error

### ISSUE THREAD

**Issue by rcoenen** [nadermx/backgroundremover#19]
Conda / Python 3.97

`backgroundremover -i test.mp4 -o test-01.png
`
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

**Comment by rcoenen** [comment]
related to this issue I suppose https://github.com/numba/numba/issues/5520

**Comment by nadermx** [comment]
Try newest release https://github.com/nadermx/backgroundremover/releases/tag/v0.2.1

**Comment by fabswt** [comment]
I still have the issue:

```
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
output.mov
Traceback (most recent call last):
  File "/opt/homebrew/bin/backgroundremover", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/backgroundremover/cmd/cli.py", line 239, in main
    remove(
  File "/opt/homebrew/lib/python3.9/site-packages/backgroundremover/bg.py", line 184, in remove
    img = Image.open(io.BytesIO(data)).convert("RGB")
  File "/opt/homebrew/lib/python3.9/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x17ff38f90>
```

This is on Python 3.11.4 (macOS Venturra 13.4) with the latest release (0.2.4).

A simple empty call will fail as well:

```
backgroundremover
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Traceback (most recent call last):
  File "/opt/homebrew/bin/backgroundremover", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/backgroundremover/cmd/cli.py", line 187, in main
    if args.input.name.rsplit('.', 1)[1] in ['mp4', 'mov', 'webm', 'ogg', 'gif']:
IndexError: list index out of range
```

**Comment by nadermx** [comment]
Can you upload the video you are trying to remove? I do 't have a
validation for no input
