### ISSUE TITLE
Intermittently, an image will yield the error: "cannot identify image file"

### ISSUE THREAD

**Issue by Slapbox** [nadermx/backgroundremover#38]
```
Traceback (most recent call last):
  File "/home/me/.local/bin/backgroundremover", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.10/site-packages/backgroundremover/cmd/cli.py", line 241, in main
    remove(
  File "/home/me/.local/lib/python3.10/site-packages/backgroundremover/bg.py", line 183, in remove
    img = Image.open(io.BytesIO(data)).convert("RGB")
  File "/home/me/.local/lib/python3.10/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fd279fa6520>
```

I wonder what could cause this? It's caused by the same set of images on every run (reproducible.) The resulting file size is 0 bytes.

PS: Thanks for sharing this awesome project!

**Comment by Slapbox** [comment]
Example:
![20](https://user-images.githubusercontent.com/6835891/183539795-26d290e1-0e4c-4d19-80fd-0eba8f62df7e.png)
 
Admittedly there's not much background to remove here - but I'm trying to do bulk processing so I don't always know the format of the images.

**Comment by Slapbox** [comment]
Interestingly, backgroundremover.app is able to handle the file without crashing - although it suffers from other problems:

![demo](https://user-images.githubusercontent.com/6835891/183548569-65bc6cd2-e000-4ead-8503-d39b14c3c864.png)

**Comment by Slapbox** [comment]
Adding a border to the images seems to help the algorithm avoid this.
