### ISSUE TITLE
Crash while saving video

### ISSUE THREAD

**Issue by RiccardoPolesel** [nadermx/backgroundremover#65]
after call
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\backgroundremover\cmd\cli.py", line 255, in <module>
    main()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\backgroundremover\cmd\cli.py", line 203, in main
    framerate=args.framerate)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\backgroundremover\utilities.py", line 231, in transparentvideo
    return "ERROR: %s" % stderr.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 11: invalid start byte

C:\Users\PC\Desktop\1>py -m backgroundremover.cmd.cli -i "1.mp4" -tv -o "out.mp4"

**Comment by nadermx** [comment]
I'm unsertain in works on windows.  I will be checking into this

**Comment by nadermx** [comment]
Please update https://github.com/nadermx/backgroundremover/releases/tag/v0.2.1

**Comment by 435781067** [comment]
FINISHED ALL FRAMES (307)!
Starting alphamerge
after call
Traceback (most recent call last):
  File "D:\Python3.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python3.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python3.10\lib\site-packages\backgroundremover\cmd\cli.py", line 253, in <module>
    main()
  File "D:\Python3.10\lib\site-packages\backgroundremover\cmd\cli.py", line 196, in main
    utilities.transparentvideo(os.path.abspath(args.output.name), os.path.abspath(args.input.name),
  File "D:\Python3.10\lib\site-packages\backgroundremover\utilities.py", line 249, in transparentvideo
    return "ERROR: %s" % stderr.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 7: invalid start byte


This bug already exists

**Comment by nadermx** [comment]
Then you must be using an old version... pip install --upgrade
backgroundremover
