### ISSUE TITLE
Error al ejecutar comando

### ISSUE THREAD

**Issue by itskreisler** [nadermx/backgroundremover#80]
## Input cmd:
```sh
python -m backgroundremover.cmd.cli -i input.jpeg -a -ae 15 -o output_.jpeg
```
## Error:

```txt
Traceback (most recent call last):
  File "D:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python310\lib\site-packages\backgroundremover\cmd\cli.py", line 253, in <module>   
    main()
  File "D:\Python\Python310\lib\site-packages\backgroundremover\cmd\cli.py", line 239, in main
    remove(
  File "D:\Python\Python310\lib\site-packages\backgroundremover\bg.py", line 188, in remove
    cutout = alpha_matting_cutout(
  File "D:\Python\Python310\lib\site-packages\backgroundremover\bg.py", line 131, in alpha_matting_cutout
    structure = np.ones((erode_structure_size, erode_structure_size), dtype=np.int)
  File "D:\Python\Python310\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current 
use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

**Comment by nadermx** [comment]
No a echo release, pero si usas el git mas recien, esto ya esta arreglado
