### ISSUE TITLE
Not Working on colab or the web app

### ISSUE THREAD

**Issue by russkiimike** [nadermx/backgroundremover#83]
Just tried to run on the colab and came across this error output 

`ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
output.mov
Traceback (most recent call last):
  File "/usr/local/bin/backgroundremover", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/backgroundremover/cmd/cli.py", line 239, in main
    remove(
  File "/usr/local/lib/python3.10/dist-packages/backgroundremover/bg.py", line 184, in remove
    img = Image.open(io.BytesIO(data)).convert("RGB")
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3030, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fc8e7c00270>`

Then double checked the web app and that too doesnt work, returns an empty file of 0kb

**Comment by nadermx** [comment]
Can you send the image/video?

**Comment by nadermx** [comment]
Fixed a issue with these types of videos, please update
