### ISSUE TITLE
How to use as a library?

### ISSUE THREAD

**Issue by BanKeTang** [nadermx/backgroundremover#95]
How to use as a library to use python to remove the background from a given image path.

**Comment by Sourland** [comment]
@BanKeTang

**Comment by Tatsh** [comment]
There is currently a circular import between `bg.py` and `utilities.py`:

```pycon
(ins)>>> from backgroundremover.bg import remove
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/backgroundremover/bg.py", line 15, in <module>
    from .u2net import detect, u2net
  File "/usr/lib/python3.11/site-packages/backgroundremover/u2net/detect.py", line 11, in <module>
    from .. import utilities
  File "/usr/lib/python3.11/site-packages/backgroundremover/utilities.py", line 9, in <module>
    from .bg import DEVICE, Net, iter_frames, remove_many
ImportError: cannot import name 'DEVICE' from partially initialized module 'backgroundremover.bg' (most likely due to a circular import) (/usr/lib/python3.11/site-packages/backgroundremover/bg.py)
```

It is possible to import from the `cli` module, but this should not be necessary.

```pycon
(ins)>>> from backgroundremover.cmd.cli import remove
(ins)>>> remove
<function remove at 0x7f27dd192ca0>
```

**Comment by ahmad88me** [comment]
I ran into the same problem. I created a pull request with the fix here: https://github.com/nadermx/backgroundremover/pull/138

**Comment by nadermx** [comment]
Fixed in https://github.com/nadermx/backgroundremover/commit/123d4445808c25521d06611e6e7e3aa9bb426b2f read ReadMe to on how to.  Tx @ahmad88me
