### ISSUE TITLE
Everything, backgroundremover for image and video, are fail

### ISSUE THREAD

**Issue by consh1** [nadermx/backgroundremover#96]
I got the error below, for running not advance but just the basic command for image backgroundremover:
`backgroundremover -i "/path/to/image.jpeg" -o "output.png"`

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/backgroundremover", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backgroundremover/cmd/cli.py", line 239, in main
    remove(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backgroundremover/bg.py", line 183, in remove
    model = get_model(model_name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backgroundremover/bg.py", line 171, in get_model
    return detect.load_model(model_name="u2net")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backgroundremover/u2net/detect.py", line 82, in load_model
    torch.load(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 2161665 more bytes. The file might be corrupted.

**And,**
I got the error below, for running not advance but just the basic command for video backgroundremover:
`backgroundremover -i "/path/to/video.mp4" -tv -o "output.mov"`

FRAME RATE DETECTED: 30/1 (if this looks wrong, override the frame rate)
FRAME RATE: 30 TOTAL FRAMES: 160
WORKER FRAMERIPPER ONLINE
WORKER 0 ONLINE
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backgroundremover/utilities.py", line 29, in worker
    net = Net(model_name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backgroundremover/bg.py", line 88, in __init__
    net.load_state_dict(torch.load(path, map_location=torch.device(DEVICE)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 2161665 more bytes. The file might be corrupted.

Could you help me to resolve these issues?

**Comment by nadermx** [comment]
do you have python-dev of what ever version of python you got?

**Comment by consh1** [comment]
python3-dev:
  Installed: 3.10.6

**Comment by nadermx** [comment]
Did you install python3.10-dev? it is different I think than python3-dev

**Comment by nadermx** [comment]
I just tried it with python3.10 after running `sudo apt install python3.10-dev` and it worked fine...
![image](https://github.com/nadermx/backgroundremover/assets/7340380/f372e62c-72e6-4083-8a52-8c385598b58f)
